"""initial

Revision ID: 263fa0ac03ac
Revises: 
Create Date: 2026-06-05 11:04:40.022197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263fa0ac03ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('messages_json', sa.Text(), nullable=True),
    sa.Column('input_data_json', sa.Text(), nullable=True),
    sa.Column('target_skill_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('dsl_expression', sa.Text(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('preset_name', sa.String(length=128), nullable=True),
    sa.Column('input_params_json', sa.Text(), nullable=True),
    sa.Column('output_params_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('chat_session_id', sa.String(length=32), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('dsl_expression', sa.Text(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('preset_name', sa.String(length=128), nullable=True),
    sa.Column('input_params_json', sa.Text(), nullable=True),
    sa.Column('output_params_json', sa.Text(), nullable=True),
    sa.Column('chat_session_id', sa.String(length=32), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_versions_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_versions_skill_id'))

    op.drop_table('skill_versions')
    op.drop_table('skills')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
