"""Chunk data model and loader — loads knowledge base chunks from AST JSONL and markdown.

Sources (in ``docs_dir``):
    ``docs/ast/*.chunks.jsonl`` — primary code KB, generated by ``build_kb_ast.py`` offline.
        Pre-split section/table_row chunks with breadcrumb/module/anchor metadata.
        kind = ``"code"``.
    ``docs/doc/*-doc.md`` — business SOP docs, kind = ``"doc"``, split by H2.
    ``docs/table/*.md`` — flat meta tables, kind = ``"meta"``, split by H2.
    ``docs/project-overview.md`` — project intro, kind = ``"meta"``, split by H2.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class Chunk:
    """A retrieval chunk — the basic unit for hybrid search and prompt construction.

    - ``chunk_id``: globally stable id (AST: ``"billing::billing/3-..."``,
      markdown: ``"billing-doc::1-changan"``). Used for dedup / RRF merge.
    - ``title``: high-density summary for dense embedding (breadcrumb, not bare heading).
    - ``body``: full text to inject into LLM prompt, with context header.
    - ``module / kind / section``: for prompt grouping and source labeling.
    - ``chunk_type``: ``"section"`` / ``"table_row"`` / ``"meta_section"``.
    - ``row``: structured field dict (table_row only), for deterministic lookup.
    - ``anchor``: markdown anchor from AST, for citation.
    """

    chunk_id: str
    title: str
    body: str
    module: str
    kind: str
    section: str
    chunk_type: str
    source: str
    anchor: str = ""
    row: dict[str, Any] | None = None
    headers: tuple[str, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# AST chunk loading (docs/ast/*.chunks.jsonl)
# ---------------------------------------------------------------------------

def _render_ast_section_body(obj: dict[str, Any]) -> str:
    breadcrumb = obj.get("breadcrumb", "")
    heading = obj.get("heading", "")
    content = obj.get("content", "") or "(This section has no body, serves as context path)"
    header = f"_{breadcrumb}_" if breadcrumb else ""
    return f"{header}\n\n## {heading}\n\n{content}".strip()


def _render_ast_table_row_body(obj: dict[str, Any]) -> str:
    breadcrumb = obj.get("breadcrumb", "")
    row = obj.get("row", {}) or {}
    lines = [f"_{breadcrumb}_  (table row)"] if breadcrumb else ["(table row)"]
    for k, v in row.items():
        lines.append(f"- **{k}**: {v}")
    return "\n".join(lines)


def _module_header_for_ast(obj: dict[str, Any]) -> str:
    return obj.get("breadcrumb") or obj.get("heading", "")


def _load_ast_chunks(ast_dir: Path) -> list[Chunk]:
    out: list[Chunk] = []
    for jsonl in sorted(ast_dir.glob("*.chunks.jsonl")):
        for line in jsonl.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            t = obj.get("type", "section")
            module = obj.get("module") or jsonl.stem.split(".")[0]
            section = obj.get("heading", "")
            if t == "table_row":
                body = _render_ast_table_row_body(obj)
            else:
                body = _render_ast_section_body(obj)
            out.append(
                Chunk(
                    chunk_id=obj.get("id", ""),
                    title=_module_header_for_ast(obj),
                    body=body,
                    module=module,
                    kind="code",
                    section=section,
                    chunk_type="section" if t == "section" else "table_row",
                    source=obj.get("source", str(jsonl)),
                    anchor=obj.get("anchor", ""),
                    row=obj.get("row"),
                    headers=tuple(obj.get("headers", []) or ()),
                )
            )
    return out


# ---------------------------------------------------------------------------
# Markdown chunk loading (docs/doc/, docs/table/, docs/project-overview.md)
# ---------------------------------------------------------------------------

_H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
_H2_SPLIT_RE = re.compile(r"^##\s+", re.MULTILINE)
_SLUG_RE = re.compile(r"[^a-z0-9一-鿿]+")
_SKIP_H2 = frozenset({"目录", "Table of Contents", "TOC"})


def _slug(s: str) -> str:
    return _SLUG_RE.sub("-", s.lower()).strip("-")


def _split_h2(text: str) -> tuple[str, list[tuple[str, str]]]:
    h1_m = _H1_RE.search(text)
    h1 = h1_m.group(1).strip() if h1_m else ""
    parts = _H2_SPLIT_RE.split(text)
    sections: list[tuple[str, str]] = []
    for part in parts[1:]:
        nl = part.find("\n")
        if nl == -1:
            title = part.strip()
            body = ""
        else:
            title = part[:nl].strip()
            body = part[nl + 1:].rstrip()
        if not title or title in _SKIP_H2:
            continue
        sections.append((title, body))
    return h1, sections


def _md_chunks(
    path: Path,
    *,
    module: str,
    kind: str,
    id_prefix: str,
) -> list[Chunk]:
    text = path.read_text(encoding="utf-8")
    h1, sections = _split_h2(text)
    out: list[Chunk] = []
    for h2_title, h2_body in sections:
        body_parts = [f"# {h1}" if h1 else "", f"## {h2_title}"]
        if h2_body:
            body_parts.append(h2_body)
        body = "\n\n".join(p for p in body_parts if p)
        breadcrumb = f"{h1} > {h2_title}" if h1 else h2_title
        out.append(
            Chunk(
                chunk_id=f"{id_prefix}::{_slug(h2_title) or 'section'}",
                title=breadcrumb,
                body=body,
                module=module,
                kind=kind,
                section=h2_title,
                chunk_type="meta_section",
                source=str(path),
            )
        )
    return out


def _classify_md(path: Path, root: Path) -> tuple[str, str]:
    stem = path.stem
    rel = path.relative_to(root).as_posix()
    if rel.startswith("doc/") and stem.endswith("-doc"):
        return stem[:-len("-doc")], "doc"
    if rel.startswith("table/"):
        return stem, "meta"
    if rel == "project-overview.md":
        return "project-overview", "meta"
    return stem.split("-", 1)[0] or "misc", "meta"


def _load_meta_and_doc_chunks(docs_dir: Path) -> list[Chunk]:
    out: list[Chunk] = []
    candidates: list[Path] = []
    for sub in ("doc", "table"):
        candidates.extend((docs_dir / sub).glob("*.md"))
    overview = docs_dir / "project-overview.md"
    if overview.is_file():
        candidates.append(overview)
    for md in sorted(candidates, key=lambda p: p.relative_to(docs_dir).as_posix()):
        module, kind = _classify_md(md, docs_dir)
        id_prefix = md.stem
        out.extend(_md_chunks(md, module=module, kind=kind, id_prefix=id_prefix))
    return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class ChunkLoader:
    """Load chunks from a docs directory.

    Usage::

        chunks = ChunkLoader.from_ast("docs/ast/")
        chunks += ChunkLoader.from_markdown("docs/")
    """

    @staticmethod
    def from_ast(ast_dir: str | Path) -> list[Chunk]:
        """Load AST-generated chunks from JSONL files."""
        path = Path(ast_dir)
        if not path.is_dir():
            return []
        return _load_ast_chunks(path)

    @staticmethod
    def from_markdown(docs_dir: str | Path) -> list[Chunk]:
        """Load markdown chunks (doc/, table/, project-overview.md)."""
        path = Path(docs_dir)
        return _load_meta_and_doc_chunks(path)

    @staticmethod
    def load_all(docs_dir: str | Path) -> list[Chunk]:
        """Load all chunks: AST first, then markdown."""
        path = Path(docs_dir)
        chunks: list[Chunk] = []
        ast_dir = path / "ast"
        if ast_dir.is_dir():
            chunks.extend(_load_ast_chunks(ast_dir))
        chunks.extend(_load_meta_and_doc_chunks(path))
        return chunks
